### ISSUE TITLE
Check pull request for deviation before writing comments

### ISSUE THREAD

**Issue by mmozuras** [mmozuras/pronto#39]
GithubPullRequestFormatter bug:

If new commits are added to a pull request, Pronto sometimes writes comments on incorrect lines. Before doing that, it should check whether pull request hasn't changed.

Reported by @ljank

**Comment by mmozuras** [comment]
@Linuus I considered it fixed, but it was reproduced in another way today. Reopening again and will try to figure it out.

**Comment by somebody32** [comment]
Got the same issue today. But pronto messes positions even without pr changes at all, just comments on the wrong lines.

Fixed by changing `line.position` to `message.line.position` https://github.com/mmozuras/pronto/blob/master/lib/pronto/formatter/github_pull_request_formatter.rb#L21

but don't think that this is a proper fix

**Comment by mmozuras** [comment]
PRs from @jhass fix this. Currently `unreleased` in `master`.
